package PPDCorba;


/**
* PPDCorba/PartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/


//
public interface PartOperations 
{

  //
  String code ();

  // codigo
  String name ();

  // nome
  String description ();
} // interface PartOperations
