package PPDCorba;

/**
* PPDCorba/PartRepositoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/


//
public final class PartRepositoryHolder implements org.omg.CORBA.portable.Streamable
{
  public PPDCorba.PartRepository value = null;

  public PartRepositoryHolder ()
  {
  }

  public PartRepositoryHolder (PPDCorba.PartRepository initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PPDCorba.PartRepositoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PPDCorba.PartRepositoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PPDCorba.PartRepositoryHelper.type ();
  }

}
