package PPDCorba;


/**
* PPDCorba/PartListItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/

public final class PartListItem implements org.omg.CORBA.portable.IDLEntity
{
  public String code = null;

  // codigo da pec'a
  public String name = null;

  public PartListItem ()
  {
  } // ctor

  public PartListItem (String _code, String _name)
  {
    code = _code;
    name = _name;
  } // ctor

} // class PartListItem
