package PPDCorba;

/**
* PPDCorba/PartHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/


//
public final class PartHolder implements org.omg.CORBA.portable.Streamable
{
  public PPDCorba.Part value = null;

  public PartHolder ()
  {
  }

  public PartHolder (PPDCorba.Part initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PPDCorba.PartHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PPDCorba.PartHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PPDCorba.PartHelper.type ();
  }

}
