package PPDCorba;


/**
* PPDCorba/PartRepositoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/


//
public abstract class PartRepositoryPOA extends org.omg.PortableServer.Servant
 implements PPDCorba.PartRepositoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_name", new java.lang.Integer (0));
    _methods.put ("_get_numParts", new java.lang.Integer (1));
    _methods.put ("addPart", new java.lang.Integer (2));
    _methods.put ("getPart", new java.lang.Integer (3));
    _methods.put ("getPartInfo", new java.lang.Integer (4));
    _methods.put ("getPartList", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //
       case 0:  // PPDCorba/PartRepository/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // nome do repositorio
       case 1:  // PPDCorba/PartRepository/_get_numParts
       {
         int $result = (int)0;
         $result = this.numParts ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //
       case 2:  // PPDCorba/PartRepository/addPart
       {
         String name = in.read_string ();
         String description = in.read_string ();
         PPDCorba.Part $result = null;
         $result = this.addPart (name, description);
         out = $rh.createReply();
         PPDCorba.PartHelper.write (out, $result);
         break;
       }


  //
       case 3:  // PPDCorba/PartRepository/getPart
       {
         try {
           String code = in.read_string ();
           PPDCorba.Part $result = null;
           $result = this.getPart (code);
           out = $rh.createReply();
           PPDCorba.PartHelper.write (out, $result);
         } catch (PPDCorba.NoSuchPart $ex) {
           out = $rh.createExceptionReply ();
           PPDCorba.NoSuchPartHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // PPDCorba/PartRepository/getPartInfo
       {
         try {
           String code = in.read_string ();
           PPDCorba.PartInfo $result = null;
           $result = this.getPartInfo (code);
           out = $rh.createReply();
           PPDCorba.PartInfoHelper.write (out, $result);
         } catch (PPDCorba.NoSuchPart $ex) {
           out = $rh.createExceptionReply ();
           PPDCorba.NoSuchPartHelper.write (out, $ex);
         }
         break;
       }


  //
       case 5:  // PPDCorba/PartRepository/getPartList
       {
         PPDCorba.PartListItem $result[] = null;
         $result = this.getPartList ();
         out = $rh.createReply();
         PPDCorba.PartListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PPDCorba/PartRepository:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PartRepository _this() 
  {
    return PartRepositoryHelper.narrow(
    super._this_object());
  }

  public PartRepository _this(org.omg.CORBA.ORB orb) 
  {
    return PartRepositoryHelper.narrow(
    super._this_object(orb));
  }


} // class PartRepositoryPOA
