package PPDCorba;


/**
* PPDCorba/PartListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/

public final class PartListHolder implements org.omg.CORBA.portable.Streamable
{
  public PPDCorba.PartListItem value[] = null;

  public PartListHolder ()
  {
  }

  public PartListHolder (PPDCorba.PartListItem[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PPDCorba.PartListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PPDCorba.PartListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PPDCorba.PartListHelper.type ();
  }

}
