package PPDCorba;


/**
* PPDCorba/PartRepositoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ppdPecas.idl
* sexta-feira, 19 de abril de 2019 00:04:39 Horário Padrão de Brasília
*/


//
abstract public class PartRepositoryHelper
{
  private static String  _id = "IDL:PPDCorba/PartRepository:1.0";

  public static void insert (org.omg.CORBA.Any a, PPDCorba.PartRepository that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PPDCorba.PartRepository extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PPDCorba.PartRepositoryHelper.id (), "PartRepository");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PPDCorba.PartRepository read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PartRepositoryStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PPDCorba.PartRepository value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PPDCorba.PartRepository narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PPDCorba.PartRepository)
      return (PPDCorba.PartRepository)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PPDCorba._PartRepositoryStub stub = new PPDCorba._PartRepositoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PPDCorba.PartRepository unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PPDCorba.PartRepository)
      return (PPDCorba.PartRepository)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PPDCorba._PartRepositoryStub stub = new PPDCorba._PartRepositoryStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
